spring.application.name=belezapro-api
server.port=8080

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Database config
spring.mongodb.uri=mongodb://root:root123@localhost:27017/belezapro_db?authSource=admin

# JWT secret (change for production)
jwt.secret=changeit-secret
cors.allowed-origins=http://localhost:4200

# Mail Configuration (Mock for Development)
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false